### ISSUE TITLE
v1 checklist

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-bootstrap#1]
Dropdowns
- [x] autocomplete #8
- [x] combo #8
- [x] dropdown #8
- [x] multiselect #8

Date Input
- [x] date picker
- [x] date time picker
- [x] timepicker
- [x] calendar

Buttons
- [x] button #6
- [x] button group #6

Inputs
- [ ] switch #10 
- [x] colorpicker #10 
- [x] masked #10 
- [x] numeric #10 
- [x] input #8
- [x] slider #10 

Layout
- [x] tabstrip #13
- [x] treeview #13
- [x] panelbar #13

Interaction
- [x] notification
- [x] tooltip
- [x] progressbar

Themes
- [ ] Default theme
- [ ] Bootstrap

Infra
- [ ] Dimension mixins
- [x] Require once mixin #2
- [x] Appearance mixins #4 
- [x] Map structure containing bootstrap variables
- [x] get-bootstrap-var function
- [x] skin descriptor mapping bs to local variables
