### ISSUE TITLE
Update Bootstrap dependency to v4.0.0-beta

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-bootstrap#298]
We've been stuck to an older version for some time now. We'll need to update to latest "stable" beta -- https://github.com/twbs/bootstrap/commit/35f80bb12e4e71fd777ee60ffa43711d8f84b1a6 or the equivalent tag.

The issues can be summarized in a few categories:

* modified variable names or removed variables, which break the build (fixed by @gyoshev)
* modified variable values, which need tweaking on our end; see checklist below
* modified variable values which differ significantly (button variables, per say)
* variable chaining or lack there of...

**Components checklist**

- [x] Button / ButtonGroup (@theOrlin)
- [x] DateInputs - Calendar, DateInput[x], DatePicker[x] (@inikolova)
- [x] Dialog (@joneff)
- [x] DropDowns - AutoComplete, ComboBox, DropDownList, MultiSelect (@inikolova) 
- [x] Forms - Checkbox, RadioButton, Switch, Textbox, Validation, Fieldset, Textarea ( @mvgmvg )
- [x] Grid (@inikolova)
- [x] Inputs - MaskedTextBox, NumericTextBox, Slider, Switch (@inikolova)
- [x] Loader ( @mvgmvg )
- [x] Menu ( @mvgmvg )
- [x] Notification ( @mvgmvg )
- [x] Pager (@inikolova)
- [x] Panelbar ( @mvgmvg )
- [x] Popup ( @mvgmvg )
- [x] ProgressBar (@theOrlin)
- [x] Tabstrip ( @mvgmvg )
- [x] TreeView ( @mvgmvg )
- [x] ToolTip ( @mvgmvg )
- [x] Upload ( @mvgmvg )
- [x] Window ( @mvgmvg )

/cc @gyoshev @inikolova @mvgmvg @theOrlin

**Comment by gyoshev** [comment]
Added some updates in the [update-bootstrap-dependency branch](https://github.com/telerik/kendo-theme-bootstrap/compare/update-bootstrap-dependency). It seems that if we handle the changes in the `theme-color-level` function, and the should go green. Not sure how the result will look, but most changes so far are changed variable names, which are handled nicely by the mapping.

**Comment by joneff** [comment]
After design review, we need to make the following change:

- [ ] Change theme-secondary color to #e4e7eb #312
- [ ] Combobox issues related to bootstrap v4 update #313
- [ ] Pickers issue related to bootstrap v4 update #314
- [ ] Multiselect issues related to bootstrap v4 update #315
- [ ] Misc issues related to bootstrap v4 update #316

/cc @mvgmvg @theOrlin
