### ISSUE TITLE
v2.0.0-beta.1 checklist

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-bootstrap#54]
## Infrastructure

- [ ] Update bootstrap
- [ ] Update variables
- [ ] Fallback variables
- [ ] Dont override html font-size in kendo demos

## Data management

- [ ] grid
  - [x] Multi-column headers must be bottom aligned
- [ ] spreadsheet
  - [x] spreadsheet dialogs (fixed by https://github.com/telerik/kendo-theme-default/pull/233)
- [ ] listview
- [ ] pivotgrid
  - [x] pivot grid outer layout is broken
- [ ] treelist
- [ ] scrollview
- [ ] pager
  - [x] missing borders
  - [x] normal state items should use `$link-text`

Approval
- [ ] designer approval for Data management
- [ ] QA approval for Data management

## Editors

- [ ] common
  - [x] popup - add rounded corners
  - [x] popup - add margin between the input and the pop-up list
  - [x] popup item - hover state background color: `background-color: #f7f7f9`
  - [x] popup header and footer - add styles
  - [x] popup group header - add styles
  - [x] the items in the item list are not positioned correctly - smaller line-height moves them up
  - [x] clear button - not properly positioned 
  - [x] focus state - dont use box-shadow
  - [x] active state - dont use box-shadow
- [ ] autocomplete
- [ ] colorpicker
- [ ] combobox
  - [x] focus state - use border color of focused input
  - [x] focus state - dont change border color between the input and buttons elements
- [ ] datepicker
- [ ] datetimepicker
- [ ] dropdownlist
  - [x] add background color to expanded dropdown
- [ ] editor
- [ ] maskedtextbox
- [ ] multiselect
- [ ] numerictextbox
  - [x] increase/decrease arrows should use button styles
- [ ] slider
  - [x] slider elements are square
  - [ ] bootstrap skin is missing ticks
- [ ] timepicker
- [ ] upload
- [ ] validator
- [ ] switch
  - [x] switch styling is not applied

Approval
- [ ] designer approval for Editors
- [ ] QA approval for Editors

 
## Dataviz

- [ ] charts
- [ ] gauges
- [ ] treemap
- [ ] barcode
- [ ] qr code
- [ ] diagram
- [ ] map
  - [x] map navigator size
  - [x] map navigator hover states

Approval
- [ ] designer approval for Dataviz
- [ ] QA approval for Dataviz

## Scheduling

- [ ] calendar
  - [x] today selected
- [ ] gantt
  - [x] reduce toolbar padding
  - [x] alt row styling
  - [x] treelist selected row
  - [x] gantt dialogs
- [ ] scheduler
  - [x] reduce toolbar padding
  - [x] check inner dimensions

Approval
- [ ] designer approval for Scheduling
- [ ] QA approval for Scheduling

## Media

- [ ] mediaplayer
  - [x] check media player styling

Approval
- [ ] designer approval for Media
- [ ] QA approval for Media
 

## Layout

- [ ] dialog
- [ ] notification
- [ ] responsive panel
- [ ] splitter
  - [x] resize handle is not visible
- [ ] tooltip
  - [x] content is always centered
- [ ] window

Approval
- [ ] designer approval for Layout
- [ ] QA approval for Layout

## Navigation

- [ ] common
  - [x] remove native focus outline
  - [x] popup - add rounded corners
  - [x] popup - styles for items in popup
  - [x] popup - add margin between the button and popup
- [ ] button
  - [x] check button group layout and extra borders
  - [x] remove box-shadow on active 
  - [x] styles of active state background and border color should be as hover state
  - [ ] add styles for outline buttons
- [ ] split button
  - [ ] border between button and split-button-arrow to change its state on hover, pressed and focus state
- [ ] buttongroup
  - [x] focus state must have higher z-index
- [ ] menu
  - [x] popup - add rounded corners
  - [ ] popup - add styles for separator
  - [x] popup item - add styles for hover `color: #1d1e1f`, `background-color: #f7f7f9`
- [ ] panelbar
  - [x] reduce padding
  - [x] use `$header-` variables for normal, hover and selected root items
  - [x] focus state - use inset box shadow with 50% opacity of the respective border
- [ ] tabstrip
  - [x] normal item should use `$link-text`
- [ ] toolbar
- [ ] treeview
  - [x] use equal padding on node items
  - [x] reduce line-height
  - [x] focused selected item box-shadow should use selected-border color
  - [x] focused state border is cut - use higher z-index

Approval
- [ ] designer approval for Navigation
- [ ] QA approval for Navigation

## Interactivity & UX

- [ ] progressbar
- [ ] styling

Approval
- [ ] designer approval for Interactivity & UX
- [ ] QA approval for Interactivity & UX

## RTL

(note: RTL is not implemented for kendo-theme-default, hence issues are expected)

- [ ] Editors
  - [ ] Expand button is incorrect styled
  - [ ] position of the "clear button"

**Comment by lkarakoleva** [comment]
## Navigation

- [ ] button
  - [ ]  remove box-shadow on active 

## Editors

- [ ] combobox
  - [ ]  add rounded corners to the pop-up container 
  - [ ]  add margin between the input and the pop-up list: margin: .125rem 0 0;
  - [ ]  remove box-shadow on active state
  - [ ]  the items in the item list are not positioned correctly - smaller line-height moves them up
  - [ ]  clear button - not properly positioned 
  - [ ]  RTL - expand button is incorrect styled; position of the "clear button" (should be fixed in default v2 as well)

- [ ] dropdownlist
  - [ ]  add rounded corners to the pop-up container 
  - [ ]  add margin between the button and the pop-up list: margin: .125rem 0 0;
  - [ ]  add active state to the expanded dropdown
  - [ ]  remove box-shadow on active state
  - [ ]  the items in the item list are not positioned correctly - smaller line-height moves them up

- [ ] maskedtextbox (textbox, input)
  - [ ]  remove box-shadow on focused state
  - [ ]  smaller height of the input: font-size: inherit

- [ ] multiselect
  - [ ]  add rounded corners to the pop-up container 
  - [ ]  add margin between the input and the pop-up list: margin: .125rem 0 0;
  - [ ]  RTL - "clear" button should be on the left side of the textbox, "close" icon should be on the left side of the token (should be fixed in default v2 as well)

- [ ] numerictextbox
  - [ ]  increase/decrease arrows should use button styles

**Comment by lkarakoleva** [comment]
## Navigation

- [ ] menu
  - [ ] add rounded corners to menu pop-up
  - [ ] menu pop-up hover item bg- `color: #1d1e1f;`, `background-color: #f7f7f9;` 
  - [ ] menu pop-up - missing styles for item separators
  - RTL support ( and for default v2)
----
- [ ] panelbar
  - [ ]  root items use $header variables for normal, hover and selected
  - [ ]  root items focused state - `box-shadow: inset 0 0 0 2px rgba($header-border/$header-hovered-border/$header-selected-border,.5)`
  - [ ]  child items focused state: `box-shadow: inset 0 0 0 2px rgba($node-border/$node-hovered-border/$node-selected-border,.5)`
----
- [ ] split button
  - [ ] remove native focus outline
  - [ ] expanded split button pop-up - there are no styles for hover, active and focus state of the items
  - [ ] add rounded corners to the pop-up container
  - [ ] add margin between the button and the pop-up list: margin: .125rem 0 0;
  - [ ] border between button and split-button-arrow to change its state on hover, pressed and focus state
----
- [ ] tabstrip
  - [ ]  unselected tab items should use `$link-text`
----
- [ ] treeview
  - [ ]  `line-height: 1.25`
  - [ ]  padding-x = padding-y
  - [ ]  padding-x = padding-y
  - [ ]  focused selected item box-shadow should use selected-border color
  - [ ]  focused state border is cut - correct z-index and position property
----
- [ ]  toolbar
  - [ ]  expanded overflow button pop-up - there are no styles for hover, active and focus state of the items, add bottom rounded corners


## Data management

- [ ] grid
  - [ ]  Multi-column headers - `vertical-align: bottom;` , missing right cell border (should be fix in default v2 as well)
  - [ ]  pager - missing borders; unselected items should use `$link-text`

**Comment by lkarakoleva** [comment]
## Data management

- [ ] grid
    - [ ] .k-grid th, .k-grid td should have `padding: .75rem;`
    - [ ] inline editing: table row should not change its height (48px) 
    - [ ] grid row = grid toolbar = grid pager (48px) 
    - [ ] grouping expand/collapse icon - add padding-right
- [ ] pager
    - [ ] incorrect `line-height: calc(1.25rem + 2px);`

## Navigation 
- [ ] menu
    - [ ] context menu: apply popup styling (for default v2 as well)

**Comment by joneff** [comment]
All outstanding issues are moved to v2.0.0-beta.2 checklist (#76)
